# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Portfolio Website - Sachin Mishra

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: Deploy to surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: ${{ secrets.surge_domain }}
        project: 'dist/angular-routing/'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
